const SUCCESS_SEND_MESSAGE = "SUCCESS_SEND_MESSAGE";
const SUCCESS_SEND_COMMENT = "SUCCESS_SEND_COMMENT";
const SUCCESS_UPDATED_FULLNAME = "SUCCESS_UPDATED_FULLNAME";
const SUCCESS_UPDATED_USERNAME = "SUCCESS_UPDATED_USERNAME";
const SUCCESS_UPDATED_BIO = "SUCCESS_UPDATED_BIO";
const SUCCESS_REGISTER = "SUCCESS_REGISTER";
const AUTHORIZED = "AUTHORIZED";
const UNAUTHORIZED = "UNAUTHORIZED";
const VALID_TOKEN = "VALID_TOKEN";
const INVALID_TOKEN = "INVALID_TOKEN";
const SUCCESS_LOGIN = "SUCCESS_LOGIN";
const MESSAGE_DELETED = "MESSAGE_DELETED";
const USER_NOT_FOUND = "USER_NOT_FOUND"

export { SUCCESS_SEND_MESSAGE, SUCCESS_SEND_COMMENT, SUCCESS_UPDATED_FULLNAME, SUCCESS_UPDATED_BIO, SUCCESS_UPDATED_USERNAME, SUCCESS_REGISTER, AUTHORIZED, UNAUTHORIZED, VALID_TOKEN, INVALID_TOKEN, SUCCESS_LOGIN, MESSAGE_DELETED, USER_NOT_FOUND };